name: hwGitActions1
on:
  push:
  pull_request:
    types: [opened, edited, reopened, closed]
jobs:
  homework:
    runs-on: ubuntu-latest
    steps:
      - name: get repo code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci --prefix server
      - name: Build
        run: npm run build --prefix server
      - name: lint
        run: npm run lint --prefix server
